interface ColorTypes {
  [key: string]: string;
  black: string;
  white: string;
  lightGrey: string;
  grey: string;
  darkGrey: string;
  lightBlue: string;
  blue: string;
  darkBlue: string;
  lightBrown: string;
  brown: string;
  darkBrown: string;
  lightTurquoise: string;
  turquoise: string;
  darkTurquoise: string;
  lightYellow: string;
  yellow: string;
  darkYellow: string;
  lightGreen: string;
  green: string;
  darkGreen: string;
  lightRed: string;
  red: string;
  darkRed: string;
  lightOrange: string;
  orange: string;
  darkOrange: string;
  lightPink: string;
  pink: string;
  darkPink: string;
  lightPurple: string;
  purple: string;
  darkPurple: string;
  fadedGreen: string;
  fadedRed: string;
  fadedBlue: string;
  fadedYellow: string;
  fadedGrey: string;
}

export const colors: ColorTypes = {
  black: '#000',
  white: '#fff',
  // greys
  fadedGrey: '#fafafa',
  lightGrey: '#dfdfdf',
  grey: '#afafaf',
  darkGrey: '#4a4a4a',
  // blues
  fadedBlue: '#d4ffff',
  lightBlue: '#add8e6',
  blue: '#0000ff',
  darkBlue: '#00008b',
  // browns
  lightBrown: '#d2b48c',
  brown: '#cd853f',
  darkBrown: '#8b4513',
  // turquoise
  lightTurquoise: '#e0ffff',
  turquoise: '#40e0d0',
  darkTurquoise: '#008080',
  // yellow
  fadedYellow: '#fff7df',
  lightYellow: '#f0e68c',
  yellow: '#ffd700',
  darkYellow: '#d4af37',
  // green
  fadedGreen: '#dfffdf',
  lightGreen: '#00c900',
  green: '#228b22',
  darkGreen: '#006400',
  // red
  fadedRed: '#ffd9d7',
  lightRed: '#ff8680',
  red: '#e70000',
  darkRed: '#a00000',
  // orange
  lightOrange: '#ffa500',
  orange: '#e96100',
  darkOrange: '#d2691e',
  // pink
  lightPink: '#fff0f5',
  pink: '#ffc0cb',
  darkPink: '#ff1493',
  // purple
  lightPurple: '#dda0dd',
  purple: '#ba55d3',
  darkPurple: '#8b008b'
};
